#! /bin/sh
#Shared bash and ZSH commands

# Shorthand command for viewing git logs
alias lg='git lg | head -30'

# Disable Ctrl-D as automatic exit from shell
set -o ignoreeof

# Ensure the vim swap directory exists
mkdir -p ~/.swp-tmp

# if fasd is installed, set it up
if hash fasd 2>/dev/null; then
  eval "$(fasd --init auto)"

  alias v='f -e vim' # quick opening files with vim
fi

# run package shell scripts
if [ -d ~/.dotfile-packages/shellrcs ]; then
  for f in ~/.dotfile-packages/shellrcs/*
  do
    source $f
  done
fi

docker_cleanup() {
  docker rm -f $(docker ps -a -q | xargs)
  docker rmi $(docker images -a -q -f dangling=true | xargs)
}

docker_cleanup_safe() {
  docker rm $(docker ps -a -q -f status=exited | xargs)
  docker rmi $(docker images -a -q -f dangling=true | xargs)
}

alias dc="docker_cleanup"
alias dcs="docker_cleanup_safe"
