#! /bin/sh
#Shared bash and ZSH commands
export GOPATH=$HOME/go_workspace
export PATH=$PATH:$GOPATH/bin
alias lg='git lg | head -30'

# Disable Ctrl-D as automatic exit from shell
set -o ignoreeof

# if fasd is installed, set it up
if hash fasd 2>/dev/null; then
  eval "$(fasd --init auto)"

  alias v='f -e vim' # quick opening files with vim
fi
